### ISSUE TITLE
Stadium 2 file list

### ISSUE THREAD

**Issue by SonikkuA-DatH** [pret/pokestadium#17]
Yo! It's Sonikku A from Discord. Couldn't find Room decos and Stadium models, but everything else should be noted here
[Stadium 2 Files.txt](https://github.com/pret/pokestadium/files/4606910/Stadium.2.Files.txt)

**Comment by ProjectRevoTPP** [comment]
Out of scope now; Stadium 2 requires a new repository since the build system changed.
